// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: models_publish.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CouponType int32

const (
	CouponType_UnknownType CouponType = 0
	CouponType_Sale        CouponType = 1
	CouponType_Cancel      CouponType = 2
	CouponType_Return      CouponType = 3
)

// Enum value maps for CouponType.
var (
	CouponType_name = map[int32]string{
		0: "UnknownType",
		1: "Sale",
		2: "Cancel",
		3: "Return",
	}
	CouponType_value = map[string]int32{
		"UnknownType": 0,
		"Sale":        1,
		"Cancel":      2,
		"Return":      3,
	}
)

func (x CouponType) Enum() *CouponType {
	p := new(CouponType)
	*p = x
	return p
}

func (x CouponType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CouponType) Descriptor() protoreflect.EnumDescriptor {
	return file_models_publish_proto_enumTypes[0].Descriptor()
}

func (CouponType) Type() protoreflect.EnumType {
	return &file_models_publish_proto_enumTypes[0]
}

func (x CouponType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CouponType.Descriptor instead.
func (CouponType) EnumDescriptor() ([]byte, []int) {
	return file_models_publish_proto_rawDescGZIP(), []int{0}
}

type PaymentType int32

const (
	PaymentType_UnknownPayment PaymentType = 0
	PaymentType_Cash           PaymentType = 1
	PaymentType_CreditCard     PaymentType = 2
	PaymentType_Voucher        PaymentType = 3
	PaymentType_Cheque         PaymentType = 4
	PaymentType_CryptoCurrency PaymentType = 5
	PaymentType_Other          PaymentType = 6
)

// Enum value maps for PaymentType.
var (
	PaymentType_name = map[int32]string{
		0: "UnknownPayment",
		1: "Cash",
		2: "CreditCard",
		3: "Voucher",
		4: "Cheque",
		5: "CryptoCurrency",
		6: "Other",
	}
	PaymentType_value = map[string]int32{
		"UnknownPayment": 0,
		"Cash":           1,
		"CreditCard":     2,
		"Voucher":        3,
		"Cheque":         4,
		"CryptoCurrency": 5,
		"Other":          6,
	}
)

func (x PaymentType) Enum() *PaymentType {
	p := new(PaymentType)
	*p = x
	return p
}

func (x PaymentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentType) Descriptor() protoreflect.EnumDescriptor {
	return file_models_publish_proto_enumTypes[1].Descriptor()
}

func (PaymentType) Type() protoreflect.EnumType {
	return &file_models_publish_proto_enumTypes[1]
}

func (x PaymentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentType.Descriptor instead.
func (PaymentType) EnumDescriptor() ([]byte, []int) {
	return file_models_publish_proto_rawDescGZIP(), []int{1}
}

type CouponItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=Price,proto3" json:"Price,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=Unit,proto3" json:"Unit,omitempty"`
	Quantity      float32                `protobuf:"fixed32,4,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Total         int64                  `protobuf:"varint,5,opt,name=Total,proto3" json:"Total,omitempty"`
	TaxRate       string                 `protobuf:"bytes,6,opt,name=TaxRate,proto3" json:"TaxRate,omitempty"`
	Type          string                 `protobuf:"bytes,7,opt,name=Type,proto3" json:"Type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponItem) Reset() {
	*x = CouponItem{}
	mi := &file_models_publish_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponItem) ProtoMessage() {}

func (x *CouponItem) ProtoReflect() protoreflect.Message {
	mi := &file_models_publish_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponItem.ProtoReflect.Descriptor instead.
func (*CouponItem) Descriptor() ([]byte, []int) {
	return file_models_publish_proto_rawDescGZIP(), []int{0}
}

func (x *CouponItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CouponItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CouponItem) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *CouponItem) GetQuantity() float32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CouponItem) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CouponItem) GetTaxRate() string {
	if x != nil {
		return x.TaxRate
	}
	return ""
}

func (x *CouponItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PaymentType            `protobuf:"varint,1,opt,name=Type,proto3,enum=atk.PaymentType" json:"Type,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_models_publish_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_models_publish_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_models_publish_proto_rawDescGZIP(), []int{1}
}

func (x *Payment) GetType() PaymentType {
	if x != nil {
		return x.Type
	}
	return PaymentType_UnknownPayment
}

func (x *Payment) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TaxGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaxRate       string                 `protobuf:"bytes,1,opt,name=TaxRate,proto3" json:"TaxRate,omitempty"`
	TotalForTax   int64                  `protobuf:"varint,2,opt,name=TotalForTax,proto3" json:"TotalForTax,omitempty"`
	TotalTax      int64                  `protobuf:"varint,3,opt,name=TotalTax,proto3" json:"TotalTax,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaxGroup) Reset() {
	*x = TaxGroup{}
	mi := &file_models_publish_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaxGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaxGroup) ProtoMessage() {}

func (x *TaxGroup) ProtoReflect() protoreflect.Message {
	mi := &file_models_publish_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaxGroup.ProtoReflect.Descriptor instead.
func (*TaxGroup) Descriptor() ([]byte, []int) {
	return file_models_publish_proto_rawDescGZIP(), []int{2}
}

func (x *TaxGroup) GetTaxRate() string {
	if x != nil {
		return x.TaxRate
	}
	return ""
}

func (x *TaxGroup) GetTotalForTax() int64 {
	if x != nil {
		return x.TotalForTax
	}
	return 0
}

func (x *TaxGroup) GetTotalTax() int64 {
	if x != nil {
		return x.TotalTax
	}
	return 0
}

type PosCoupon struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BusinessId     uint64                 `protobuf:"varint,1,opt,name=BusinessId,proto3" json:"BusinessId,omitempty"`
	CouponId       uint64                 `protobuf:"varint,2,opt,name=CouponId,proto3" json:"CouponId,omitempty"`
	BranchId       uint64                 `protobuf:"varint,3,opt,name=BranchId,proto3" json:"BranchId,omitempty"`
	Location       string                 `protobuf:"bytes,4,opt,name=Location,proto3" json:"Location,omitempty"`
	OperatorId     string                 `protobuf:"bytes,5,opt,name=OperatorId,proto3" json:"OperatorId,omitempty"`
	PosId          uint64                 `protobuf:"varint,6,opt,name=PosId,proto3" json:"PosId,omitempty"`
	ApplicationId  uint64                 `protobuf:"varint,7,opt,name=ApplicationId,proto3" json:"ApplicationId,omitempty"`
	VerificationNo string                 `protobuf:"bytes,8,opt,name=VerificationNo,proto3" json:"VerificationNo,omitempty"`
	Type           CouponType             `protobuf:"varint,9,opt,name=Type,proto3,enum=atk.CouponType" json:"Type,omitempty"`
	Time           int64                  `protobuf:"varint,10,opt,name=Time,proto3" json:"Time,omitempty"`
	Items          []*CouponItem          `protobuf:"bytes,11,rep,name=Items,proto3" json:"Items,omitempty"`
	Payments       []*Payment             `protobuf:"bytes,12,rep,name=Payments,proto3" json:"Payments,omitempty"`
	Total          int64                  `protobuf:"varint,13,opt,name=Total,proto3" json:"Total,omitempty"`
	TaxGroups      []*TaxGroup            `protobuf:"bytes,14,rep,name=TaxGroups,proto3" json:"TaxGroups,omitempty"`
	TotalTax       int64                  `protobuf:"varint,15,opt,name=TotalTax,proto3" json:"TotalTax,omitempty"`
	TotalNoTax     int64                  `protobuf:"varint,16,opt,name=TotalNoTax,proto3" json:"TotalNoTax,omitempty"`
	ReferenceNo    uint64                 `protobuf:"varint,17,opt,name=ReferenceNo,proto3" json:"ReferenceNo,omitempty"`
	TransactionNo  uint64                 `protobuf:"varint,18,opt,name=TransactionNo,proto3" json:"TransactionNo,omitempty"`
	TotalDiscount  int64                  `protobuf:"varint,19,opt,name=TotalDiscount,proto3" json:"TotalDiscount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PosCoupon) Reset() {
	*x = PosCoupon{}
	mi := &file_models_publish_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PosCoupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosCoupon) ProtoMessage() {}

func (x *PosCoupon) ProtoReflect() protoreflect.Message {
	mi := &file_models_publish_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosCoupon.ProtoReflect.Descriptor instead.
func (*PosCoupon) Descriptor() ([]byte, []int) {
	return file_models_publish_proto_rawDescGZIP(), []int{3}
}

func (x *PosCoupon) GetBusinessId() uint64 {
	if x != nil {
		return x.BusinessId
	}
	return 0
}

func (x *PosCoupon) GetCouponId() uint64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *PosCoupon) GetBranchId() uint64 {
	if x != nil {
		return x.BranchId
	}
	return 0
}

func (x *PosCoupon) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *PosCoupon) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *PosCoupon) GetPosId() uint64 {
	if x != nil {
		return x.PosId
	}
	return 0
}

func (x *PosCoupon) GetApplicationId() uint64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *PosCoupon) GetVerificationNo() string {
	if x != nil {
		return x.VerificationNo
	}
	return ""
}

func (x *PosCoupon) GetType() CouponType {
	if x != nil {
		return x.Type
	}
	return CouponType_UnknownType
}

func (x *PosCoupon) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *PosCoupon) GetItems() []*CouponItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PosCoupon) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *PosCoupon) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PosCoupon) GetTaxGroups() []*TaxGroup {
	if x != nil {
		return x.TaxGroups
	}
	return nil
}

func (x *PosCoupon) GetTotalTax() int64 {
	if x != nil {
		return x.TotalTax
	}
	return 0
}

func (x *PosCoupon) GetTotalNoTax() int64 {
	if x != nil {
		return x.TotalNoTax
	}
	return 0
}

func (x *PosCoupon) GetReferenceNo() uint64 {
	if x != nil {
		return x.ReferenceNo
	}
	return 0
}

func (x *PosCoupon) GetTransactionNo() uint64 {
	if x != nil {
		return x.TransactionNo
	}
	return 0
}

func (x *PosCoupon) GetTotalDiscount() int64 {
	if x != nil {
		return x.TotalDiscount
	}
	return 0
}

type CitizenCoupon struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BusinessId     uint64                 `protobuf:"varint,1,opt,name=BusinessId,proto3" json:"BusinessId,omitempty"`
	CouponId       uint64                 `protobuf:"varint,2,opt,name=CouponId,proto3" json:"CouponId,omitempty"`
	BranchId       uint64                 `protobuf:"varint,3,opt,name=BranchId,proto3" json:"BranchId,omitempty"`
	PosId          uint64                 `protobuf:"varint,4,opt,name=PosId,proto3" json:"PosId,omitempty"`
	VerificationNo uint64                 `protobuf:"varint,5,opt,name=VerificationNo,proto3" json:"VerificationNo,omitempty"`
	Type           CouponType             `protobuf:"varint,6,opt,name=Type,proto3,enum=atk.CouponType" json:"Type,omitempty"`
	Time           int64                  `protobuf:"varint,7,opt,name=Time,proto3" json:"Time,omitempty"`
	Total          int64                  `protobuf:"varint,8,opt,name=Total,proto3" json:"Total,omitempty"`
	TaxGroups      []*TaxGroup            `protobuf:"bytes,9,rep,name=TaxGroups,proto3" json:"TaxGroups,omitempty"`
	TotalTax       int64                  `protobuf:"varint,10,opt,name=TotalTax,proto3" json:"TotalTax,omitempty"`
	TotalNoTax     int64                  `protobuf:"varint,11,opt,name=TotalNoTax,proto3" json:"TotalNoTax,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CitizenCoupon) Reset() {
	*x = CitizenCoupon{}
	mi := &file_models_publish_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CitizenCoupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CitizenCoupon) ProtoMessage() {}

func (x *CitizenCoupon) ProtoReflect() protoreflect.Message {
	mi := &file_models_publish_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CitizenCoupon.ProtoReflect.Descriptor instead.
func (*CitizenCoupon) Descriptor() ([]byte, []int) {
	return file_models_publish_proto_rawDescGZIP(), []int{4}
}

func (x *CitizenCoupon) GetBusinessId() uint64 {
	if x != nil {
		return x.BusinessId
	}
	return 0
}

func (x *CitizenCoupon) GetCouponId() uint64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *CitizenCoupon) GetBranchId() uint64 {
	if x != nil {
		return x.BranchId
	}
	return 0
}

func (x *CitizenCoupon) GetPosId() uint64 {
	if x != nil {
		return x.PosId
	}
	return 0
}

func (x *CitizenCoupon) GetVerificationNo() uint64 {
	if x != nil {
		return x.VerificationNo
	}
	return 0
}

func (x *CitizenCoupon) GetType() CouponType {
	if x != nil {
		return x.Type
	}
	return CouponType_UnknownType
}

func (x *CitizenCoupon) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *CitizenCoupon) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CitizenCoupon) GetTaxGroups() []*TaxGroup {
	if x != nil {
		return x.TaxGroups
	}
	return nil
}

func (x *CitizenCoupon) GetTotalTax() int64 {
	if x != nil {
		return x.TotalTax
	}
	return 0
}

func (x *CitizenCoupon) GetTotalNoTax() int64 {
	if x != nil {
		return x.TotalNoTax
	}
	return 0
}

type QrCoupon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessId    uint64                 `protobuf:"varint,1,opt,name=BusinessId,proto3" json:"BusinessId,omitempty"`
	CouponId      uint64                 `protobuf:"varint,2,opt,name=CouponId,proto3" json:"CouponId,omitempty"`
	BranchId      uint64                 `protobuf:"varint,3,opt,name=BranchId,proto3" json:"BranchId,omitempty"`
	PosId         uint64                 `protobuf:"varint,4,opt,name=PosId,proto3" json:"PosId,omitempty"`
	Type          CouponType             `protobuf:"varint,5,opt,name=Type,proto3,enum=atk.CouponType" json:"Type,omitempty"`
	Time          int64                  `protobuf:"varint,6,opt,name=Time,proto3" json:"Time,omitempty"`
	Total         int64                  `protobuf:"varint,7,opt,name=Total,proto3" json:"Total,omitempty"`
	TaxGroups     []*TaxGroup            `protobuf:"bytes,8,rep,name=TaxGroups,proto3" json:"TaxGroups,omitempty"`
	TotalTax      int64                  `protobuf:"varint,9,opt,name=TotalTax,proto3" json:"TotalTax,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QrCoupon) Reset() {
	*x = QrCoupon{}
	mi := &file_models_publish_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QrCoupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QrCoupon) ProtoMessage() {}

func (x *QrCoupon) ProtoReflect() protoreflect.Message {
	mi := &file_models_publish_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QrCoupon.ProtoReflect.Descriptor instead.
func (*QrCoupon) Descriptor() ([]byte, []int) {
	return file_models_publish_proto_rawDescGZIP(), []int{5}
}

func (x *QrCoupon) GetBusinessId() uint64 {
	if x != nil {
		return x.BusinessId
	}
	return 0
}

func (x *QrCoupon) GetCouponId() uint64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *QrCoupon) GetBranchId() uint64 {
	if x != nil {
		return x.BranchId
	}
	return 0
}

func (x *QrCoupon) GetPosId() uint64 {
	if x != nil {
		return x.PosId
	}
	return 0
}

func (x *QrCoupon) GetType() CouponType {
	if x != nil {
		return x.Type
	}
	return CouponType_UnknownType
}

func (x *QrCoupon) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *QrCoupon) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QrCoupon) GetTaxGroups() []*TaxGroup {
	if x != nil {
		return x.TaxGroups
	}
	return nil
}

func (x *QrCoupon) GetTotalTax() int64 {
	if x != nil {
		return x.TotalTax
	}
	return 0
}

var File_models_publish_proto protoreflect.FileDescriptor

const file_models_publish_proto_rawDesc = "" +
	"\n" +
	"\x14models_publish.proto\x12\x03atk\"\xaa\x01\n" +
	"\n" +
	"CouponItem\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Price\x18\x02 \x01(\x03R\x05Price\x12\x12\n" +
	"\x04Unit\x18\x03 \x01(\tR\x04Unit\x12\x1a\n" +
	"\bQuantity\x18\x04 \x01(\x02R\bQuantity\x12\x14\n" +
	"\x05Total\x18\x05 \x01(\x03R\x05Total\x12\x18\n" +
	"\aTaxRate\x18\x06 \x01(\tR\aTaxRate\x12\x12\n" +
	"\x04Type\x18\a \x01(\tR\x04Type\"G\n" +
	"\aPayment\x12$\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x10.atk.PaymentTypeR\x04Type\x12\x16\n" +
	"\x06Amount\x18\x02 \x01(\x03R\x06Amount\"b\n" +
	"\bTaxGroup\x12\x18\n" +
	"\aTaxRate\x18\x01 \x01(\tR\aTaxRate\x12 \n" +
	"\vTotalForTax\x18\x02 \x01(\x03R\vTotalForTax\x12\x1a\n" +
	"\bTotalTax\x18\x03 \x01(\x03R\bTotalTax\"\xfa\x04\n" +
	"\tPosCoupon\x12\x1e\n" +
	"\n" +
	"BusinessId\x18\x01 \x01(\x04R\n" +
	"BusinessId\x12\x1a\n" +
	"\bCouponId\x18\x02 \x01(\x04R\bCouponId\x12\x1a\n" +
	"\bBranchId\x18\x03 \x01(\x04R\bBranchId\x12\x1a\n" +
	"\bLocation\x18\x04 \x01(\tR\bLocation\x12\x1e\n" +
	"\n" +
	"OperatorId\x18\x05 \x01(\tR\n" +
	"OperatorId\x12\x14\n" +
	"\x05PosId\x18\x06 \x01(\x04R\x05PosId\x12$\n" +
	"\rApplicationId\x18\a \x01(\x04R\rApplicationId\x12&\n" +
	"\x0eVerificationNo\x18\b \x01(\tR\x0eVerificationNo\x12#\n" +
	"\x04Type\x18\t \x01(\x0e2\x0f.atk.CouponTypeR\x04Type\x12\x12\n" +
	"\x04Time\x18\n" +
	" \x01(\x03R\x04Time\x12%\n" +
	"\x05Items\x18\v \x03(\v2\x0f.atk.CouponItemR\x05Items\x12(\n" +
	"\bPayments\x18\f \x03(\v2\f.atk.PaymentR\bPayments\x12\x14\n" +
	"\x05Total\x18\r \x01(\x03R\x05Total\x12+\n" +
	"\tTaxGroups\x18\x0e \x03(\v2\r.atk.TaxGroupR\tTaxGroups\x12\x1a\n" +
	"\bTotalTax\x18\x0f \x01(\x03R\bTotalTax\x12\x1e\n" +
	"\n" +
	"TotalNoTax\x18\x10 \x01(\x03R\n" +
	"TotalNoTax\x12 \n" +
	"\vReferenceNo\x18\x11 \x01(\x04R\vReferenceNo\x12$\n" +
	"\rTransactionNo\x18\x12 \x01(\x04R\rTransactionNo\x12$\n" +
	"\rTotalDiscount\x18\x13 \x01(\x03R\rTotalDiscount\"\xdd\x02\n" +
	"\rCitizenCoupon\x12\x1e\n" +
	"\n" +
	"BusinessId\x18\x01 \x01(\x04R\n" +
	"BusinessId\x12\x1a\n" +
	"\bCouponId\x18\x02 \x01(\x04R\bCouponId\x12\x1a\n" +
	"\bBranchId\x18\x03 \x01(\x04R\bBranchId\x12\x14\n" +
	"\x05PosId\x18\x04 \x01(\x04R\x05PosId\x12&\n" +
	"\x0eVerificationNo\x18\x05 \x01(\x04R\x0eVerificationNo\x12#\n" +
	"\x04Type\x18\x06 \x01(\x0e2\x0f.atk.CouponTypeR\x04Type\x12\x12\n" +
	"\x04Time\x18\a \x01(\x03R\x04Time\x12\x14\n" +
	"\x05Total\x18\b \x01(\x03R\x05Total\x12+\n" +
	"\tTaxGroups\x18\t \x03(\v2\r.atk.TaxGroupR\tTaxGroups\x12\x1a\n" +
	"\bTotalTax\x18\n" +
	" \x01(\x03R\bTotalTax\x12\x1e\n" +
	"\n" +
	"TotalNoTax\x18\v \x01(\x03R\n" +
	"TotalNoTax\"\x90\x02\n" +
	"\bQrCoupon\x12\x1e\n" +
	"\n" +
	"BusinessId\x18\x01 \x01(\x04R\n" +
	"BusinessId\x12\x1a\n" +
	"\bCouponId\x18\x02 \x01(\x04R\bCouponId\x12\x1a\n" +
	"\bBranchId\x18\x03 \x01(\x04R\bBranchId\x12\x14\n" +
	"\x05PosId\x18\x04 \x01(\x04R\x05PosId\x12#\n" +
	"\x04Type\x18\x05 \x01(\x0e2\x0f.atk.CouponTypeR\x04Type\x12\x12\n" +
	"\x04Time\x18\x06 \x01(\x03R\x04Time\x12\x14\n" +
	"\x05Total\x18\a \x01(\x03R\x05Total\x12+\n" +
	"\tTaxGroups\x18\b \x03(\v2\r.atk.TaxGroupR\tTaxGroups\x12\x1a\n" +
	"\bTotalTax\x18\t \x01(\x03R\bTotalTax*?\n" +
	"\n" +
	"CouponType\x12\x0f\n" +
	"\vUnknownType\x10\x00\x12\b\n" +
	"\x04Sale\x10\x01\x12\n" +
	"\n" +
	"\x06Cancel\x10\x02\x12\n" +
	"\n" +
	"\x06Return\x10\x03*s\n" +
	"\vPaymentType\x12\x12\n" +
	"\x0eUnknownPayment\x10\x00\x12\b\n" +
	"\x04Cash\x10\x01\x12\x0e\n" +
	"\n" +
	"CreditCard\x10\x02\x12\v\n" +
	"\aVoucher\x10\x03\x12\n" +
	"\n" +
	"\x06Cheque\x10\x04\x12\x12\n" +
	"\x0eCryptoCurrency\x10\x05\x12\t\n" +
	"\x05Other\x10\x06B\tZ\a./protob\x06proto3"

var (
	file_models_publish_proto_rawDescOnce sync.Once
	file_models_publish_proto_rawDescData []byte
)

func file_models_publish_proto_rawDescGZIP() []byte {
	file_models_publish_proto_rawDescOnce.Do(func() {
		file_models_publish_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_publish_proto_rawDesc), len(file_models_publish_proto_rawDesc)))
	})
	return file_models_publish_proto_rawDescData
}

var file_models_publish_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_models_publish_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_models_publish_proto_goTypes = []any{
	(CouponType)(0),       // 0: atk.CouponType
	(PaymentType)(0),      // 1: atk.PaymentType
	(*CouponItem)(nil),    // 2: atk.CouponItem
	(*Payment)(nil),       // 3: atk.Payment
	(*TaxGroup)(nil),      // 4: atk.TaxGroup
	(*PosCoupon)(nil),     // 5: atk.PosCoupon
	(*CitizenCoupon)(nil), // 6: atk.CitizenCoupon
	(*QrCoupon)(nil),      // 7: atk.QrCoupon
}
var file_models_publish_proto_depIdxs = []int32{
	1, // 0: atk.Payment.Type:type_name -> atk.PaymentType
	0, // 1: atk.PosCoupon.Type:type_name -> atk.CouponType
	2, // 2: atk.PosCoupon.Items:type_name -> atk.CouponItem
	3, // 3: atk.PosCoupon.Payments:type_name -> atk.Payment
	4, // 4: atk.PosCoupon.TaxGroups:type_name -> atk.TaxGroup
	0, // 5: atk.CitizenCoupon.Type:type_name -> atk.CouponType
	4, // 6: atk.CitizenCoupon.TaxGroups:type_name -> atk.TaxGroup
	0, // 7: atk.QrCoupon.Type:type_name -> atk.CouponType
	4, // 8: atk.QrCoupon.TaxGroups:type_name -> atk.TaxGroup
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_models_publish_proto_init() }
func file_models_publish_proto_init() {
	if File_models_publish_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_publish_proto_rawDesc), len(file_models_publish_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_publish_proto_goTypes,
		DependencyIndexes: file_models_publish_proto_depIdxs,
		EnumInfos:         file_models_publish_proto_enumTypes,
		MessageInfos:      file_models_publish_proto_msgTypes,
	}.Build()
	File_models_publish_proto = out.File
	file_models_publish_proto_goTypes = nil
	file_models_publish_proto_depIdxs = nil
}
